import torch
from transformers import Speech2TextProcessor, Speech2TextForConditionalGeneration
import warnings

# Suppressing extraneous Hugging Face future warnings to keep terminal readable
warnings.simplefilter('ignore')

class ModelInference:
    def __init__(self, model_id="facebook/s2t-small-librispeech-asr"):
        """Initializes the Speech-to-Text Model and Processor for inference."""
        print(f"Loading Model and Processor for: {model_id}...")
        
        # Load the processor (needed for decoding token IDs back to string)
        self.processor = Speech2TextProcessor.from_pretrained(model_id)
        
        # Load the core Model logic (the Transformer mechanism itself)
        self.model = Speech2TextForConditionalGeneration.from_pretrained(model_id)
        print("[OK] Model successfully loaded and ready for inference.")

    def transcribe(self, inputs):
        """
        Takes inputs (input_features, attention_mask) generated by Module 3,
        runs model.generate(), and decodes the model's token IDs to a text string.
        """
        print("\nRunning Model Inference (Generating Text)...")
        
        # Validate that the necessary dictionary keys are present
        if not hasattr(inputs, "input_features") or inputs.input_features is None:
            print("[ERROR] Error: Missing 'input_features' in inputs parameter.")
            return None
            
        try:
            # 1. Generation Step: Model analyses Log-Mel features mapped under input_features
            # and uses attention_mask to safely ignore padding.
            # Generated Output is mathematical Token IDs.
            generated_ids = self.model.generate(
                inputs.input_features, 
                attention_mask=inputs.attention_mask if hasattr(inputs, "attention_mask") else None
            )
            
            # 2. Decoding Step: Convert resulting Token ID sequence backward into English string
            # while filtering out internal structural tokens (e.g. padding and eos tokens).
            transcription = self.processor.batch_decode(generated_ids, skip_special_tokens=True)
            
            # Transcription is returned as a list, we return the primary 0-index match
            final_text = transcription[0]
            print("[OK] Inference Complete!")
            return final_text
            
        except Exception as e:
            print(f"[ERROR] Transcription failed during inference: {e}")
            return None

    def generate_tokens(self, inputs):
        """
        Takes inputs (input_features, attention_mask) generated by Module 3,
        and runs model.generate() to strictly output the Token IDs for downstream processing.
        """
        print("\nRunning Model Inference (Generating Token IDs)...")
        
        # Validate that the necessary dictionary keys are present
        if not hasattr(inputs, "input_features") or inputs.input_features is None:
            print("[ERROR] Error: Missing 'input_features' in inputs parameter.")
            return None
            
        try:
            generated_ids = self.model.generate(
                inputs.input_features, 
                attention_mask=inputs.attention_mask if hasattr(inputs, "attention_mask") else None
            )
            print("[OK] Token generation complete!")
            return generated_ids
            
        except Exception as e:
            print(f"[ERROR] Token generation failed during inference: {e}")
            return None

# Local Debug Testing System
if __name__ == "__main__":
    print("Welcome to Module 4 Engine Component System!")
    
    # 1. Simulate the inputs arriving cleanly from Module 3 (feature_extractor.py)
    # We will import the exact class from the local directory to show integration
    try:
        from feature_extractor import FeatureExtractor
        import numpy as np
        
        extractor = FeatureExtractor()
        
        # We artificially generate exactly 2 seconds of purely fake, static audio
        print("\nGenerating simulated static audio data (2 seconds)...")
        dummy_audio = np.random.randn(32000).astype(np.float32)
        
        # Module 3 output
        model_inputs = extractor.extract(dummy_audio, sampling_rate=16000)
    except ImportError:
        print("[ERROR] Cannot find feature_extractor.py natively to test integration.")
        model_inputs = None
        
    if model_inputs is not None:
        # 2. We initialize our new Inference architectural sequence and process inputs
        inference_engine = ModelInference()
        text_output = inference_engine.transcribe(model_inputs)
        
        # 3. Print Final Output
        print("\n[OUTPUT] Final Transcribed Text: ")
        print(f"--> '{text_output}'")
        print("\n(Note: The string is empty or gibberish because we fed it random mathematical noise instead of a real voice!)")
